name: Test Speed Comparion 

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Run-RTL-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci
    
    - name: Generate Test Case
      run: npm run generate

    - name: Timed RTL Test
      run: time npm test

  Run-Storybook-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci
    
    - name: Generate Test Case
      run: npm run generate
    
    - name: Generate Storybook
      run: npm run build-storybook

    - name: Timed Storybook Test
      run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on http://127.0.0.1:6006 && time npm run test-storybook"
